version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: []
    schedule:
      interval: "daily"
    groups:
      github-actions-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "pip"
    groups:
      pip-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "pip"
    groups:
      uv-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"
    groups:
      npm-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"
    groups:
      bun-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
